# Generated by Django 4.2.1 on 2023-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionapp', '0005_alter_ex_post_only_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nowon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('cafe', models.CharField(max_length=100)),
                ('mountain', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Lion_Post',
        ),
    ]
