# Generated by Django 4.2.1 on 2023-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionapp', '0004_rename_update_timw_ex_post_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex_post',
            name='only_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
