# Generated by Django 4.2.1 on 2023-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lionapp', '0006_nowon_delete_lion_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
