# Generated by Django 4.2.1 on 2023-05-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lionapp', '0007_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='pos',
        ),
    ]
